name: vocab_sender

on:
  schedule:
    - cron: "*/30 * * * *"

  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Pull image
        run: docker pull jackdiva/vocab_sender:latest

      - name: Run container
        run: |
          docker run --rm \
            -e CSV_PATH=/app/vocab_data \
            -e OPEN_ROUTER_KEY="${{ secrets.OPENROUTER_API_KEY }}" \
            -e MODEL_ID="${{ secrets.MODEL_ID }}" \
            -e TELEGRAM_KEY="${{ secrets.TELEGRAM_KEY }}" \
            -e TELEGRAM_CHAT_ID="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -v ${{ github.workspace }}/vocab_data:/app/vocab_data:ro \
            jackdiva/vocab_sender:latest
